os:
  - linux
  - osx
services:
  - xvfb
env:
  global:
    - DISPLAY=$(if [[ $TRAVIS_OS_NAME == "linux" ]]; then echo ':99.0'; fi)
    - MOZ_XVFB=$(if [[ $TRAVIS_OS_NAME == "linux" ]]; then echo 1; fi)
  matrix:
    - NODE_VERSION="10"  # Maintenance LTS
    - NODE_VERSION="lts/*"
    - NODE_VERSION="node"
before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - export NODE=$(nvm which $NODE_VERSION)
  - export NPM=${NODE%node}npm
install:
  - $NPM install
script:
  - $NPM test
  - $NPM run coveralls
